export const chatList = [
  {
    id: 0,
    isGroupChat: true,
    chatName: "Grupa NOVOakademii",
    users: [
      { id: 0, username: "Admin1" },
      { id: 1, username: "Admin2" },
      { id: 2, username: "User1" },
      { id: 3, username: "User2" },
      { id: 4, username: "User3" },
      { id: 5, username: "User4" },
      { id: 6, username: "User5" },
      { id: 7, username: "User6" },
    ],
    messages: [
      {
        id_message: 0,
        user_message: { id: 1 },
        text: "hello",
      },
      {
        id_message: 1,
        user_message: { id: 2 },
        text: "hi",
      },
      {
        id_message: 2,
        user_message: { id: 3 },
        text: "fsfsfsdfs",
      },
      {
        id_message: 3,
        user_message: { id: 4 },
        text: "jytuytu",
      },
    ],
  },
]

export const userDataBase = [
  {
    id: 0,
    username: "Admin1",
    password: "admin",
    isAdmin: true,
    isLogged: false,
    chatList: [...chatList],
  },
  {
    id: 1,
    username: "Admin2",
    password: "admin",
    isAdmin: true,
    isLogged: false,
    chatList: [...chatList],
  },
  {
    id: 2,
    username: "User1",
    password: "user",
    isAdmin: false,
    isLogged: false,
    chatList: [chatList[0]],
  },
  {
    id: 3,
    username: "User2",
    password: "user2",
    isAdmin: false,
    isLogged: false,
    chatList: [chatList[0]],
  },
  {
    id: 4,
    username: "User3",
    password: "user3",
    isAdmin: false,
    isLogged: false,
    chatList: [chatList[0]],
  },
  {
    id: 5,
    username: "User4",
    password: "user3",
    isAdmin: false,
    isLogged: false,
    chatList: [chatList[0]],
  },
  {
    id: 6,
    username: "User5",
    password: "user3",
    isAdmin: false,
    isLogged: false,
    chatList: [chatList[0]],
  },
  {
    id: 7,
    username: "User6",
    password: "user3",
    isAdmin: false,
    isLogged: false,
    chatList: [chatList[0]],
  },
]
